shazow/ssh-chat

server.go
Example:
```$ ssh localhost
* mcroydon joined. (Total connected: 1)
[mcroydon] /nick REALLYLONGNAMETHATISGOINGTOGETTRUNCATED
* mcroydon is now known as REALLYLONGNAMETHATISGOINGTOGETTR.
```
=> Display possibly truncated nickname when processing /nick commands.

auth.go, cmd.go
My SSH key is passphrase protected. As such, you can't simply read it and feed the byte string to `ssh.ParsePrivateKey`. You first have to unlock it with your passphrase.
This feature implements the ability to accept a passphrase (either on command line or from STDIN), decrypts the key, and then passes it along unencrypted to `ssh.ParsePrivateKey`.
Tested with RSA, and DSA with and without passphrases. My version of OpenSSH wasn't built with EC support so I can't test ECDSA.
=> Adding passphrase prompt and CLI flag.

README.md, cmd.go, sshd/doc.go
I also printed port information upon startup, which is what I think #76 was looking for, but this can be moved in to info-level logging if we don't want to see it all the time. Here's an example of the new startup output:
```
$ ./ssh-chat
Listening for connections on 0.0.0.0:2022
```
Open to painting that bikeshed differently.
=> Default port to 2022, updating documentation to match new default.

Makefile, README.md, auth.go, chat/command.go
Fixes #129:
* Tells `go get` to fetch the packages needed by cmd/ssh-chat/...
* Also do this in `make deps`; hopefully that fixes the CI tests
* Also have `$(BUILD)` depend on the `deps` target, so that `make build` works on systems that haven't downloaded all the dependencies yet
Fixes #130:
* pass by reference into AllowAnonymous
* check return value of From() rather than value of From function
=> Clarify README.md; fix `go vet` nitpicks; fix `make deps` for CI tests; fix `make build`

chat/command.go, chat/message/user.go, chat/room.go, chat/room_test.go, chat/set_test.go, common/set.go
Added the ability to ignore other users.
`/ignore [USER]` ignores messages from the provided user. Calling `/ignore` without parameters will display the list of currently ignored users.
`/unignore USER` will remove the ignored user from the ignored list, so to receive its messages again.
Upon reconnecting the ignored messages are displayed normally, but this should be the desired behavior.
=> Add `/ignore`/`/unignore` commands

chat/message/theme.go
This fixes a zero division error for themes with only one color.
=> Fixing zero division error for one color themes

chat/message/theme.go
Similar to #190, except now this uses a solarized dark theme using their accents for user names. System messages should be visible now on solarized dark terminals (discussed in #160).
Here's a sample using solarized dark on Terminator.
Hacker green theme is the same as #190.
=> Themes: Adding Solarized Dark and Mono Green (hacker)

sshd/auth.go
Fixes #214 - adds the "SHA256" prefix in all public key fingerprint cases.
=> Add SHA256 prefix to pubkey fingerprints

chat/command.go
Shows all themes on an empty `/theme` call. Not a very friendly way to join all the strings since all the Theme names are locked behind `theme.ID()`. It's either do each ID call in each cycle of the loop and add it to a string, or build a list of all the Theme names, then use String.Join to merge them all together and use that. (Third option: have a list of all theme strings somewhere to avoid having to do iteration/list building every time someone calls `/theme`?)
=> command.go: modifying Theme command to show all available themes

.travis.yml, chat/sanitize.go
This will help catch issues like https://github.com/shazow/ssh-chat/pull/240#discussion_r127626103 in CI.
If you want to be even more strict and require all Go code to be simplified, then you can add `-s` option to gofmt, like I've done [here](https://github.com/shurcooL/home/blob/728df9104b79c381fc135d7725be3550cd19a361/.travis.yml#L14). Since it's not my repository, I went with the more permissive option by default.
=> Travis: Check for gofmt issues.

chat/command.go
In reference to #205.
`/names` output is now colored with the user's current theme. The upside is that it makes `/names` more appealing. The downside is clients that don't support ANSI escape codes might see a lot of garbage output instead of simple names. I'm not sure how to work around that issue itself.
How `/names` looks with the available themes:
I can add a check that skips the coloring if the selected theme is mono. That way a user can at least avoid getting garbage output from `/names` when they have no ANSI support.
=> Colorize /name output with selected theme

cmd/ssh-chat/cmd.go, logger.go
os.Exit does not run defered calls, i changed os.Exit(0) to return because they do the same thing but return will execute defered calls. also clarified imports :)
I could create a slice of global cleanup functions and execute them in fail (like what i did [here](https://github.com/UlisseMini/clean)) but i'm not sure if its really worth it since all you're doing is closing a few files.
=> cmd: Code cleanup

Makefile, NOTICE, go.mod, go.sum, host.go, host_test.go, sshd/terminal.go, sshd/terminal/LICENSE, sshd/terminal/NOTICE, sshd/terminal/terminal.go, sshd/terminal/terminal_test.go, sshd/terminal/util.go, sshd/terminal/util_aix.go, sshd/terminal/util_bsd.go, sshd/terminal/util_linux.go, sshd/terminal/util_plan9.go, sshd/terminal/util_solaris.go, sshd/terminal/util_windows.go
Fixes #305 
Rendering issues in this PR:
=> Fork golang.org/x/crypto/ssh/terminal, remove echo override hack

sshd/terminal/terminal.go
Added key code handling for shortcuts:
- Alt-F: jump **f**orward by a word
- Alt-B: jump **b**ackword by a word
- Ctrl-F: jump **f**orward by a character
- Ctrl-B: jump **b**ackword by a character
these are congruent with the spec provided by [readline](http://man7.org/linux/man-pages/man3/readline.3.html) and are used by shells like bash & zsh.
=> Added additional key code for prompt navigation

go.mod, go.sum, sshd/terminal/terminal.go, sshd/terminal/terminal_test.go
Fix for #336,
- I believe it's about text width handling, some of runes (e.g. "端" or "子" in #336) are fullwidth, means need two characters space to display in terminal.
- So import ["golang.org/x/text/width"](https://pkg.go.dev/golang.org/x/text/width) in visualLength() to help counting the width like t.prompt do. And with a test TestTerminalvisualLength.
- However moveCursorToPos() now depends on t.line, maybe there is a better place to achieve this ?
=> sshd/terminal: Add fullwidth check for CJK in visualLength

chat/message/user.go, host.go, sshd/terminal.go
This is the beginning of the bot and api modes for ssh-chat.
Primarily, it disables our custom re-rendering pipeline (which emits a slew of control characters that are increasingly hard to parse for bots), it also disables the message echo'ing and defaults to the mono theme. Should be a very clean output that is easy to parse.
This should also make testing easier.
Comparing outputs, default: (using `cat -A`)
```
^[[38;05;245m * me joined. (Connected: 1)^[[0m^M^M$
[^[[38;05;88mme^[[0m] 
```
TERM=bot:
```
* me joined. (Connected: 1)^M^M$
```
=> TERM=bot mode

cmd/ssh-chat/cmd.go, sshd/auth.go
Fixes #288
Looks like this:
Updated usage:
```
Usage:
ssh-chat [OPTIONS]
Application Options:
-v, --verbose            Show verbose logging.
--version            Print version and exit.
-i, --identity=          Private key to identify server with. (default: ~/.ssh/id_rsa)
--bind=              Host and port to listen on. (default: 0.0.0.0:2022)
--admin=             File of public keys who are admins.
--whitelist=         Optional file of public keys who are allowed to connect.
--motd=              Optional Message of the Day file.
--log=               Write chat log to this file.
--pprof=             Enable pprof http server for profiling.
Help Options:
-h, --help               Show this help message
There are hidden options and easter eggs in ssh-chat. The source code is a good
place to …
```
=> main: Add --unsafe-passphrase

sshd/terminal.go
This will allow for TERM to be set even if no pty is requested. Simplifies making bots a bit.
=> sshd: Terminal.Term() fallback to Env TERM

chat/message/message.go, chat/room.go, chat/room_test.go
=> Ignored people still show up when they `/msg` and `/me` emote

chat/message/user.go, chat/room.go, host.go, identity.go
Primarily to be used to make Github sponsors be special.
=> chat, main: Add /rename op command, optional symbol prefix

host.go
Fixes https://github.com/shazow/ssh-chat/issues/360
You were right @shazow 👍🏽 
I was careful and kept symbol into to sent message notification (`Sent PM to <symbol> <user>`)
=> Fix ~ Reply to user with symbol returning Err user not found

Makefile
Build on MacOS M1 chip successfully.
```
Packaged: ssh-chat-darwin_arm64.tgz
CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 LDFLAGS='-X main.Version=v1.11-rc1-6-g3557bf7 -extldflags "-static"' ./build_release "github.com/shazow/ssh-chat/cmd/ssh-chat" README.md LICENSE
Defaulting to BUILDDIR=build
a ssh-chat
a ssh-chat/LICENSE
a ssh-chat/README.md
a ssh-chat/ssh-chat
```
=> Add build script for apple silicon

host.go, host_test.go
We were trying to set config based on environment variables before the user was registered in the host. This changes fixes it by moves the configuration step.
I liked the feature so i put a test on it.
=> Fix SSHCHAT_TIMESTAMP env variables

auth.go, auth_test.go, cmd/ssh-chat/cmd.go, sshd/auth.go, sshd/client_test.go
Password authentication is now completely handled in Auth. The normal
keyboard-interactive handler checks if passwords are supported and asks
for them, removing the need to override the callbacks.
Brute force throttling is removed; I'd like to base it on IP address
banning, which requires changes to the checks.
Specifically, if it's OK, I'd like to move IP and client ban checks to a new ``CheckBans``
which is called from the keyboard-interactive and public-key callbacks.
Then, a failed password could ban the IP for a configurable amount of time.
This does remove "can't be banned" status of people with a password, though.
I'm not sure, but I think timing attacks against the password are fixed:
- The hashing of the real password happens only at startup.
- The hashing of a provided password …
=> Move password authentication handling into sshd/auth (fixes #394).

set/set.go, set/set_test.go
=> Allow adding expired items to sets and make Set.cleanup work.

README.md, docker-compose.yml
* Add SSH keys mount (mimicking default non-Docker behaviour).
* Increase manifest version to lowest 3.x supporting bind mounts.
* Change restart policy from `always` to `unless-stopped`.
* Set a container name.
* Fix port indentation to 2 spaces, as done elsewhere.
Also, minor markdown tweaks on readme.
=> Docker Compose manifest: mount host's keys and few other improvements.

host.go
A basic logic change to avoid writing message-of-the-day text to the user if they connect with `TERM=bot` during the initial connection.
=> host.go: avoiding motd output if bot mode set

chat/message/message.go
In reference to #414.
When `t == nil`, no theme is selected, and this is the way to indicate that `TERM=bot` is set.
The logic is branched, and `user.ID()` is used in place of `user.Name()`. The text used in `fmt.Sprintf` is separated and could be lifted from the function and used as a constant instead to avoid repeated allocations if desired (if the Go compiler doesn't do that already in the build step).
=> Fixing emojis being sent in PMs when no theme is set (#414)
