- chat/channel.go
- chat/channel_test.go
- chat/command.go
- chat/user.go
Adds "quiet" mode for the new refactor branch with tests :star2:
> Adding test and impl for quiet mode.

- client.go
This PR adds two new commands:
- /unban  
To unban a fingerprint
- /banned  
To list all banned fingerprints
> Unban fingerprint & List banned fingerprints

- chat/command.go
- chat/help.go
- chat/message/history.go
- chat/message/history_test.go
- chat/message/identity.go
- chat/message/logger.go
- chat/message/message.go
- chat/message/message_test.go
- chat/message/screen_test.go
- chat/message/theme.go
- chat/message/theme_test.go
- chat/message/user.go
- chat/message/user_test.go
- chat/room.go
- chat/room_test.go
- chat/set.go
- chat/set_test.go
- cmd.go
- host.go
- host_test.go
- identity.go
Moved ssh-chat/chat/{message,user,theme,history} -> ssh-chat/chat/message
Fairly chunky change, but might make godoc cleaner to read? Right now there is *a lot* in http://godoc.org/github.com/shazow/ssh-chat/chat
> Create chat/message package?

- cmd/ssh-chat/cmd.go
- sshd/net.go
- sshd/ratelimit.go
> More forgiving connection limiter

- README.md
>  Add this project to GoDoc

- cmd/ssh-chat/key.go
This allows people to build the program.
> Updated the URL for the 'gopass' dependency

- chat/sanitize.go
> Limit user name length

- .gitmodules
- host.go
- host_test.go
- identity.go
- sshd/terminal.go
Resolves #170.
First time contributing to this project, so I'm not yet familiar with the practices here. There was no CONTRIBUTING.md with special instructions to follow (aside from https://github.com/shazow/ssh-chat#compiling--developing), so I just did everything the normal way.
I asked if you're okay with a new dependency [here](https://github.com/shazow/ssh-chat/issues/170#issuecomment-238048884), and you didn't say no yet, so I used it for now.
I don't usually vendor dependencies in my projects, but I see you do, so I tried to as well. I haven't used git submodules in the past, so I don't know if I did that right.
Feedback to get this into mergable state is welcome.
> /whois: Hide IP if user isn't admin, display client and time joined.

- host.go
> Attempted confirmation message for /msg sender

- README.md
> Readme: Adding section for FAQs

- cmd/ssh-chat/cmd.go
> remove strings.TrimSpace from motd parsing

- host.go
> format /uptime output with go-humanize

- .gitmodules
- Makefile
- build_release
- cmd/ssh-chat/key.go
This swaps out the gopass dependency as mentioned in #217.  I was able to cross compile for Windows without any issue, so I added that in too.
> Windows build

- host.go
Wrapping the reply action within a Host.GetUser() check to safely assure that the user being replied to is still online. This should resolve #228.
Screenshot included demo'ing the fix:
> host.go: Fixing bug with /reply

- chat/doc.go
Found a little typo and a grammar error while digging thru ssh-chat's lovely source
> Typo and odd grammar fix

- set/set_test.go
> Fix #187, test case 3

- CONTRIBUTING.md
- issue_template.md
Adding a guideline file for contributing to the project. Included as well is an issue template to deal with bug reports. Wording and style is subject to change.
> CONTRIBUTING.md and Issue Template

- .travis.yml
- go.mod
- go.sum
> Switch to go modules, update travisci for go 1.11

- chat/command.go
> ignore arguments to /shrug

- logger.go
ioutil.Discard is made for this, no need to use a bytes.Buffer
> logger: change nil bytes.Buffer into ioutil.Discard

- chat/command.go
- chat/message/message.go
- chat/message/theme.go
- chat/message/user.go
- chat/room.go
- host.go
- host_test.go
I have mixed feelings about this. It's not great, could be improved. Not sure if I'll get a chance to improve it anytime soon though.
Definitely no timezone support, or even per-second resolution. If this opens up those cans of worms, I'm going to be sad.
> Freakin' Timestamps On Every Freakin' Line

- chat/message/user.go
- chat/room.go
- chat/room_test.go
I think this is a better solution than sorting by shortest.
Fixes #204
> chat: Sort NamesPrefix by recently active

- sshd/terminal/util.go
Go is dumb so we have to remove this
> Remove commented import

- go.mod
- sshd/net.go
> sshd: Apply read deadline to connection handler

- sshd/terminal/util_solaris.go
Fix issue with go1.13+
See https://github.com/golang/go/issues/37747
> Remove import comment. Fixes #337

- chat/command.go
first time I've done a PR, no clue if I'm doing it right, but here you go. the code you wrote inserted where you told me haha, submitted.
> chat: Sort /names output

- chat/command.go
- chat/message/user.go
- set/set.go
Also prepares set to be generalized for other user identity types in a wrapper.
> /focus: Add command to only show messages from focused users

- chat/command.go
- chat/command_test.go
Changes:
* Added `/back` command
* Test cases for all permutations of `/away` commands
> Added /back and tests for all away commands

- host_test.go
Fixed the test by using user joined callback instead of relying on the go scheduler to do the expected thing >_>
> Fixed flaky user name collision test

- README.md
Hello!
Just wanted to update the README to match the newest options. Thanks for the excellent program!
> README: Change whitelist to allowlist
